### ISSUE TITLE
Profile "Current Job" is Editable

### ISSUE THREAD

**Issue by toantonyh** [dry1ce/ProConnect#2]
In a user profile page, the "Current Job:" in the "Current Job" edit field should not be editable.  Only the content after "Current Job:" should be editable.

"Current Job" field should behave the same way as "Previous Job" and "Education" fields.

![capture](https://cloud.githubusercontent.com/assets/9190572/7112397/f5fc6a62-e17d-11e4-9033-17ea696ddcbd.PNG)

**Comment by dry1ce** [comment]
That's because "Current job" was meant to be a placeholder. It should be replaced with the job.

**Comment by toantonyh** [comment]
fixed.
